mod window;
pub use window::GLFWWindow;
mod gl_;
pub use gl_::Gl;

use crate::Key;

pub(self) fn glfw_key_to_key(glfw_key: glfw::Key) -> Option<Key> {
    use crate::Key as K;
    use glfw::Key as G;

    let key = match glfw_key {
        G::Space => K::Space,
        G::Apostrophe => K::Apostrophe,
        G::Comma => K::Comma,
        G::Minus => K::Minus,
        G::Period => K::Period,
        G::Slash => K::Slash,
        G::Num0 => K::Num0,
        G::Num1 => K::Num1,
        G::Num2 => K::Num2,
        G::Num3 => K::Num3,
        G::Num4 => K::Num4,
        G::Num5 => K::Num5,
        G::Num6 => K::Num6,
        G::Num7 => K::Num7,
        G::Num8 => K::Num8,
        G::Num9 => K::Num9,
        G::Semicolon => K::Semicolon,
        G::Equal => K::Equals,
        G::A => K::A,
        G::B => K::B,
        G::C => K::C,
        G::D => K::D,
        G::E => K::E,
        G::F => K::F,
        G::G => K::G,
        G::H => K::H,
        G::I => K::I,
        G::J => K::J,
        G::K => K::K,
        G::L => K::L,
        G::M => K::M,
        G::N => K::N,
        G::O => K::O,
        G::P => K::P,
        G::Q => K::Q,
        G::R => K::R,
        G::S => K::S,
        G::T => K::T,
        G::U => K::U,
        G::V => K::V,
        G::W => K::W,
        G::X => K::X,
        G::Y => K::Y,
        G::Z => K::Z,
        G::LeftBracket => K::LeftBracket,
        G::Backslash => K::Backslash,
        G::RightBracket => K::RightBracket,
        G::GraveAccent => K::Grave,
        G::Escape => K::Escape,
        G::Enter => K::Enter,
        G::Tab => K::Tab,
        G::Backspace => K::Backspace,
        G::Insert => K::Insert,
        G::Delete => K::Delete,
        G::Right => K::ArrowRight,
        G::Left => K::ArrowLeft,
        G::Down => K::ArrowDown,
        G::Up => K::ArrowUp,
        G::PageUp => K::PageUp,
        G::PageDown => K::PageDown,
        G::Home => K::Home,
        G::End => K::End,
        G::CapsLock => K::CapsLock,
        G::F1 => K::F1,
        G::F2 => K::F2,
        G::F3 => K::F3,
        G::F4 => K::F4,
        G::F5 => K::F5,
        G::F6 => K::F6,
        G::F7 => K::F7,
        G::F8 => K::F8,
        G::F9 => K::F9,
        G::F10 => K::F10,
        G::F11 => K::F11,
        G::F12 => K::F12,
        G::LeftShift | G::RightShift => K::Shift,
        G::LeftControl | G::RightControl => K::Control,
        G::LeftAlt | G::RightAlt => K::Alt,
        G::LeftSuper | G::RightSuper => K::Meta,
        _ => return None,
    };

    Some(key)
}
